# ───────────────────────────────────────────────────────────────────
# VENDORED FROM: ai-signal-generator/app/prompt/builder.py
# DO NOT EDIT THIS FILE DIRECTLY.
# Run `make sync-vendored` from repo root after upstream changes.
# Build will fail if checksums do not match.
# ───────────────────────────────────────────────────────────────────
"""
Prompt assembler for the AI signal generator.
Builds the full context string from AgentState data + a DB-loaded template.
No LLM calls — pure text assembly.
"""

import logging
from datetime import datetime, timezone
from typing import Any

from app._vendored.prompt_templates import load_template

logger = logging.getLogger(__name__)

_SEP = '═' * 59


def _v(value: Any, default: str = 'N/A') -> str:
    if value is None:
        return default
    return str(value)


# ── Section renderers ──────────────────────────────────────────────────────────

def _render_header(state: dict) -> str:
    sc       = state['strategy_config']
    base     = sc.get('base_asset', 'BTC')
    quote    = sc.get('quote_asset', 'USDT')
    interval = state.get('cycle_interval', '?')
    ts       = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')
    trigger  = state.get('trigger_reason', 'scheduled')

    lines = [
        _SEP,
        f"MATP AI ANALYSIS — {base}-{quote} — {interval}",
        f"Generated: {ts} UTC",
        f"Analysis Trigger: {trigger}",
        _SEP,
    ]

    if state.get('position_open'):
        side      = _v(state.get('position_side'))
        entry     = _v(state.get('position_entry_price'))
        pnl_pct   = _v(state.get('position_unrealized_pnl_pct'))
        opened_at = state.get('position_opened_at')
        reasoning = state.get('original_reasoning')

        time_str = 'N/A'
        if opened_at is not None:
            try:
                if isinstance(opened_at, str):
                    opened_at = datetime.fromisoformat(opened_at)
                now = datetime.now(timezone.utc)
                if opened_at.tzinfo is None:
                    opened_at = opened_at.replace(tzinfo=timezone.utc)
                delta    = now - opened_at
                hours    = int(delta.total_seconds() // 3600)
                minutes  = int((delta.total_seconds() % 3600) // 60)
                time_str = f"{hours}h {minutes}m"
            except Exception:
                pass

        lines += [
            '',
            '⚠️  ACTIVE POSITION — EXIT EVALUATION MODE',
            f'Direction:     {side}',
            f'Entry Price:   {entry}',
            f'Current P&L:   {pnl_pct}%',
            f'Time Open:     {time_str}',
        ]
        if reasoning:
            lines.append(f'Original Thesis: "{reasoning}"')

    return '\n'.join(lines)


def _render_technical(state: dict) -> str:
    ohlcv    = state.get('ohlcv_data') or {}
    ind      = state.get('technical_indicators') or {}
    interval = state.get('cycle_interval', '?')

    lines = [f"TECHNICAL INDICATORS ({interval} timeframe):"]

    if ohlcv:
        lines += [
            f"Current Price:    {_v(ohlcv.get('current_price'))}",
            f"24h Change:       {_v(ohlcv.get('price_change_24h_pct'))}%",
            f"7d Change:        {_v(ohlcv.get('price_change_7d_pct'))}%",
            '',
        ]

    if 'rsi_14' in ind:
        lines.append(
            f"RSI(14):          {ind['rsi_14']} — {ind.get('rsi_interpretation', '')}"
        )
    if 'macd_hist' in ind:
        lines.append(
            f"MACD:             hist {ind['macd_hist']}, "
            f"signal cross {ind.get('macd_signal_bars', 0)} bars ago"
        )
    if 'ema_cross_status' in ind:
        cross = ind.get('ema_cross_status', '')
        ema50  = ind.get('ema_50')
        ema200 = ind.get('ema_200')
        suffix = f" (EMA50={ema50} / EMA200={ema200})" if ema50 and ema200 else ''
        lines.append(f"EMA 50/200:       {cross}{suffix}")
    if 'bb_interpretation' in ind:
        lines.append(f"BB:               {ind['bb_interpretation']}")
    if 'vwap_deviation_pct' in ind:
        lines.append(
            f"VWAP:             price {ind['vwap_deviation_pct']}% "
            f"{ind.get('vwap_direction', '')} VWAP"
        )
    if 'atr_14' in ind:
        lines.append(
            f"ATR(14):          {ind['atr_14']} ({ind.get('atr_pct_of_price', 'N/A')}% of price)"
        )
    if 'volume_vs_avg_pct' in ind:
        vol_pct = ind['volume_vs_avg_pct']
        direction = 'above' if vol_pct >= 0 else 'below'
        lines.append(
            f"Volume (vs 20MA):  {abs(vol_pct)}% {direction} average"
        )

    if 'support_1' in ind or 'resistance_1' in ind:
        lines += ['', 'Key Levels:']
        if 'support_1' in ind:
            lines.append(f"  Nearest Support:    {ind['support_1']}")
        if 'resistance_1' in ind:
            lines.append(f"  Nearest Resistance: {ind['resistance_1']}")

    return '\n'.join(lines)


def _render_sentiment(state: dict) -> str:
    sc = state['strategy_config']
    sd = state.get('sentiment_data') or {}

    body: list[str] = []

    if sc.get('use_fear_greed'):
        fg = sd.get('fear_greed')
        if fg:
            body.append(f"Fear & Greed Index:   {fg['value']} ({fg['label']})")

    if sc.get('use_funding_rate'):
        fr = sd.get('funding_rate')
        if fr:
            body.append(f"Funding Rate:         {fr['rate']}% ({fr['interpretation']})")

    if sc.get('use_open_interest'):
        oi = sd.get('open_interest')
        if oi:
            oi_usd    = float(oi.get('open_interest_usd') or 0)
            oi_b      = oi_usd / 1_000_000_000
            ch        = oi.get('change_24h_pct', 0)
            ls_ratio  = oi.get('long_short_ratio')
            ls_interp = oi.get('ls_interpretation', 'data unavailable')
            body.append(f"Open Interest:        ${oi_b:.2f}B ({ch}% 24h)")
            body.append(f"Long/Short Ratio:     {_v(ls_ratio)} ({ls_interp})")

    if not body:
        return ''
    return 'SENTIMENT:\n' + '\n'.join(body)


def _render_news(state: dict) -> str:
    nd = state.get('news_data')
    sc = state['strategy_config']
    lookback = sc.get('lookback_days', 1) * 24

    if isinstance(nd, dict):
        items    = nd.get('items', [])
        lookback = nd.get('lookback_hours', lookback)
    elif isinstance(nd, list):
        items = nd
    else:
        items = []

    lines = [f"NEWS DIGEST (last {lookback} hours):"]
    if items:
        for item in items[:10]:
            sev      = item.get('severity', 'medium').upper()
            headline = item.get('headline', '')
            lines.append(f"[{sev}] {headline}")
    else:
        lines.append("No significant news in the lookback window.")

    return '\n'.join(lines)


def _render_macro(state: dict) -> str:
    sc = state['strategy_config']
    mc = state.get('market_context') or {}

    lines: list[str] = []

    if sc.get('use_btc_dominance'):
        bd = mc.get('btc_dominance')
        if bd:
            lines.append(
                f"BTC Dominance:        {bd.get('btc_dominance', 'N/A')}% "
                f"({bd.get('btc_dom_trend', 'N/A')})"
            )

    if sc.get('use_macro'):
        m = mc.get('macro')
        if m:
            if 'dxy' in m:
                lines.append(f"DXY:                  {m['dxy']} ({m.get('dxy_trend', 'N/A')})")
            if 'us10y' in m:
                lines.append(f"US10Y:                {m['us10y']}% ({m.get('us10y_trend', 'N/A')})")

    return '\n'.join(lines)


def _render_portfolio(state: dict) -> str:
    rc       = state.get('risk_config') or {}
    max_size = _v(rc.get('max_position_size_pct'))

    lines = [
        'PORTFOLIO CONTEXT:',
        'Account Balance:      (resolved at execution time)',
        f"Max Position Size:    {max_size}%",
    ]
    if not state.get('position_open'):
        lines.append("Last Signal:          N/A")

    return '\n'.join(lines)


def _render_task(state: dict) -> str:
    position_open = state.get('position_open', False)
    position_side = state.get('position_side') or 'long'

    lines = [_SEP, 'YOUR TASK:']

    if position_open:
        close_action = f"close_{position_side}"
        lines += [
            f"Evaluate whether the original thesis for this {position_side} position is still valid.",
            "Consider all new data since the position was opened.",
            'If the thesis is intact: output "hold" or "adjust_stops" with updated levels.',
            'If the thesis is weakening: output "partial_close".',
            f'If the thesis is invalidated or a new risk is present: output "{close_action}".',
            'If the position is showing strong continuation: output "increase" (only if within size limits).',
        ]
    else:
        lines += [
            "Identify whether current market conditions present a high-conviction trade setup.",
            'If a setup exists: output "open_long" or "open_short" with full parameters.',
            'If conditions are unclear or insufficient confluence: output "hold".',
        ]

    lines += [
        '',
        'CONFIDENCE SCALE:',
        '0.50-0.65: Speculative — below threshold, will be rejected',
        '0.65-0.75: Moderate — meets minimum threshold',
        '0.75-0.85: High conviction — clear confluence',
        '0.85-0.95: Exceptional setup — multiple independent signals aligned',
        'Never output confidence above 0.95.',
        '',
        'OUTPUT: Structured JSON only. reasoning field must cite specific indicator values.',
        _SEP,
    ]

    return '\n'.join(lines)


# ── Public API ─────────────────────────────────────────────────────────────────

async def build_prompt(state: dict, db_pool) -> str:
    """
    Assemble the full LLM prompt from AgentState and a DB-loaded template.
    No LLM calls. Returns the complete prompt string.
    """
    sc          = state['strategy_config']
    template_id = sc.get('template_id', 'trend_following')
    template    = await load_template(template_id, db_pool)

    sections: list[str] = []

    # 1. Header — always included; contains position warning if position_open
    sections.append(_render_header(state))

    # 2. Technical — only if toggled on and OHLCV data is available
    if sc.get('use_technical') and state.get('ohlcv_data'):
        sections.append(_render_technical(state))

    # 3. Sentiment — only if at least one sentiment source is toggled on
    if sc.get('use_fear_greed') or sc.get('use_funding_rate') or sc.get('use_open_interest'):
        s = _render_sentiment(state)
        if s:
            sections.append(s)

    # 4. News — only if toggled on and digest is available
    if sc.get('use_news') and state.get('news_data'):
        sections.append(_render_news(state))

    # 5. Macro — only if at least one macro source is toggled on
    if sc.get('use_btc_dominance') or sc.get('use_macro'):
        m = _render_macro(state)
        if m:
            sections.append(m)

    # 6. Portfolio — always included
    sections.append(_render_portfolio(state))

    # 7. Data warnings — inserted between portfolio and instructions if errors occurred
    errors = state.get('data_fetch_errors') or []
    if errors:
        warn_lines = ['DATA WARNINGS:'] + [f'  - {e}' for e in errors]
        sections.append('\n'.join(warn_lines))

    # 8. Strategy instructions — from DB template, always included
    if template:
        inst = ['STRATEGY INSTRUCTIONS:', template['system_prompt']]
        custom = sc.get('custom_instructions')
        if custom:
            inst += ['', 'ADDITIONAL RULES:', custom]
        sections.append('\n'.join(inst))

    # 9. Task section — always included
    sections.append(_render_task(state))

    return '\n\n'.join(filter(None, sections))


def get_estimated_tokens(prompt: str) -> int:
    return len(prompt) // 4
