VENDORED_DIR := strategy-tester/app/_vendored

.PHONY: sync-vendored check-vendored build

sync-vendored:
	@mkdir -p $(VENDORED_DIR)
	@cp ai-signal-generator/app/graph/nodes/node_analyze.py $(VENDORED_DIR)/node_analyze.py
	@cp ai-signal-generator/app/data/indicators.py $(VENDORED_DIR)/indicators.py
	@cp ai-signal-generator/app/prompt/builder.py $(VENDORED_DIR)/prompt_builder.py
	@cp ai-signal-generator/app/prompt/templates.py $(VENDORED_DIR)/prompt_templates.py
	@sed -i 's|from app\.prompt\.templates|from app._vendored.prompt_templates|g' $(VENDORED_DIR)/prompt_builder.py
	@sed -i 's|from app\.prompt\.builder|from app._vendored.prompt_builder|g' $(VENDORED_DIR)/node_analyze.py
	@{ printf '# ───────────────────────────────────────────────────────────────────\n# VENDORED FROM: ai-signal-generator/app/graph/nodes/node_analyze.py\n# DO NOT EDIT THIS FILE DIRECTLY.\n# Run `make sync-vendored` from repo root after upstream changes.\n# Build will fail if checksums do not match.\n# ───────────────────────────────────────────────────────────────────\n'; cat $(VENDORED_DIR)/node_analyze.py; } > $(VENDORED_DIR)/node_analyze.py.tmp && mv $(VENDORED_DIR)/node_analyze.py.tmp $(VENDORED_DIR)/node_analyze.py
	@{ printf '# ───────────────────────────────────────────────────────────────────\n# VENDORED FROM: ai-signal-generator/app/data/indicators.py\n# DO NOT EDIT THIS FILE DIRECTLY.\n# Run `make sync-vendored` from repo root after upstream changes.\n# Build will fail if checksums do not match.\n# ───────────────────────────────────────────────────────────────────\n'; cat $(VENDORED_DIR)/indicators.py; } > $(VENDORED_DIR)/indicators.py.tmp && mv $(VENDORED_DIR)/indicators.py.tmp $(VENDORED_DIR)/indicators.py
	@{ printf '# ───────────────────────────────────────────────────────────────────\n# VENDORED FROM: ai-signal-generator/app/prompt/builder.py\n# DO NOT EDIT THIS FILE DIRECTLY.\n# Run `make sync-vendored` from repo root after upstream changes.\n# Build will fail if checksums do not match.\n# ───────────────────────────────────────────────────────────────────\n'; cat $(VENDORED_DIR)/prompt_builder.py; } > $(VENDORED_DIR)/prompt_builder.py.tmp && mv $(VENDORED_DIR)/prompt_builder.py.tmp $(VENDORED_DIR)/prompt_builder.py
	@{ printf '# ───────────────────────────────────────────────────────────────────\n# VENDORED FROM: ai-signal-generator/app/prompt/templates.py\n# DO NOT EDIT THIS FILE DIRECTLY.\n# Run `make sync-vendored` from repo root after upstream changes.\n# Build will fail if checksums do not match.\n# ───────────────────────────────────────────────────────────────────\n'; cat $(VENDORED_DIR)/prompt_templates.py; } > $(VENDORED_DIR)/prompt_templates.py.tmp && mv $(VENDORED_DIR)/prompt_templates.py.tmp $(VENDORED_DIR)/prompt_templates.py
	@cd $(VENDORED_DIR) && sha256sum *.py > CHECKSUMS
	@echo "sync-vendored complete. CHECKSUMS written."

check-vendored:
	@cd $(VENDORED_DIR) && sha256sum -c CHECKSUMS

build: sync-vendored
	docker compose build strategy-tester tester-ui
